<?php

use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_municipios')->insert([
            ['distrito_id'  =>  1, 'municipio' => 'Acajete', 'clave' => '1'],
            ['distrito_id'  =>  1, 'municipio' => 'Acatlán', 'clave' => '2'],
            ['distrito_id'  =>  1, 'municipio' => 'Acayucan', 'clave' => '3'],
            ['distrito_id'  =>  1, 'municipio' => 'Actopan', 'clave' => '4'],
            ['distrito_id'  =>  1, 'municipio' => 'Acula', 'clave' => '5'],
            ['distrito_id'  =>  1, 'municipio' => 'Acultzingo', 'clave' => '6'],
            ['distrito_id'  =>  1, 'municipio' => 'Camarón de Tejeda', 'clave' => '7'],
            ['distrito_id'  =>  1, 'municipio' => 'Alpatláhuac', 'clave' => '8'],
            ['distrito_id'  =>  1, 'municipio' => 'Alto Lucero de Gutiérrez Barrios', 'clave' => '9'],
            ['distrito_id'  =>  1, 'municipio' => 'Altotonga', 'clave' => '10'],
            ['distrito_id'  =>  1, 'municipio' => 'Alvarado', 'clave' => '11'],
            ['distrito_id'  =>  1, 'municipio' => 'Amatitlán', 'clave' => '12'],
            ['distrito_id'  =>  1, 'municipio' => 'Naranjos Amatlán', 'clave' => '13'],
            ['distrito_id'  =>  1, 'municipio' => 'Amatlán de los Reyes', 'clave' => '14'],
            ['distrito_id'  =>  1, 'municipio' => 'Angel R. Cabada', 'clave' => '15'],
            ['distrito_id'  =>  1, 'municipio' => 'La Antigua', 'clave' => '16'],
            ['distrito_id'  =>  1, 'municipio' => 'Apazapan', 'clave' => '17'],
            ['distrito_id'  =>  1, 'municipio' => 'Aquila', 'clave' => '18'],
            ['distrito_id'  =>  1, 'municipio' => 'Astacinga', 'clave' => '19'],
            ['distrito_id'  =>  1, 'municipio' => 'Atlahuilco', 'clave' => '20'],
            ['distrito_id'  =>  1, 'municipio' => 'Atoyac', 'clave' => '21'],
            ['distrito_id'  =>  1, 'municipio' => 'Atzacan', 'clave' => '22'],
            ['distrito_id'  =>  1, 'municipio' => 'Atzalan', 'clave' => '23'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlaltetela', 'clave' => '24'],
            ['distrito_id'  =>  1, 'municipio' => 'Ayahualulco', 'clave' => '25'],
            ['distrito_id'  =>  1, 'municipio' => 'Banderilla', 'clave' => '26'],
            ['distrito_id'  =>  1, 'municipio' => 'Benito Juárez', 'clave' => '27'],
            ['distrito_id'  =>  1, 'municipio' => 'Boca del Río', 'clave' => '28'],
            ['distrito_id'  =>  1, 'municipio' => 'Calcahualco', 'clave' => '29'],
            ['distrito_id'  =>  1, 'municipio' => 'Camerino Z. Mendoza', 'clave' => '30'],
            ['distrito_id'  =>  1, 'municipio' => 'Carrillo Puerto', 'clave' => '31'],
            ['distrito_id'  =>  1, 'municipio' => 'Catemaco', 'clave' => '32'],
            ['distrito_id'  =>  1, 'municipio' => 'Cazones de Herrera', 'clave' => '33'],
            ['distrito_id'  =>  1, 'municipio' => 'Cerro Azul', 'clave' => '34'],
            ['distrito_id'  =>  1, 'municipio' => 'Citlaltépetl', 'clave' => '35'],
            ['distrito_id'  =>  1, 'municipio' => 'Coacoatzintla', 'clave' => '36'],
            ['distrito_id'  =>  1, 'municipio' => 'Coahuitlán', 'clave' => '37'],
            ['distrito_id'  =>  1, 'municipio' => 'Coatepec', 'clave' => '38'],
            ['distrito_id'  =>  1, 'municipio' => 'Coatzacoalcos', 'clave' => '39'],
            ['distrito_id'  =>  1, 'municipio' => 'Coatzintla', 'clave' => '40'],
            ['distrito_id'  =>  1, 'municipio' => 'Coetzala', 'clave' => '41'],
            ['distrito_id'  =>  1, 'municipio' => 'Colipa', 'clave' => '42'],
            ['distrito_id'  =>  1, 'municipio' => 'Comapa', 'clave' => '43'],
            ['distrito_id'  =>  1, 'municipio' => 'Córdoba', 'clave' => '44'],
            ['distrito_id'  =>  1, 'municipio' => 'Cosamaloapan de Carpio', 'clave' => '45'],
            ['distrito_id'  =>  1, 'municipio' => 'Cosautlán de Carvajal', 'clave' => '46'],
            ['distrito_id'  =>  1, 'municipio' => 'Coscomatepec', 'clave' => '47'],
            ['distrito_id'  =>  1, 'municipio' => 'Cosoleacaque', 'clave' => '48'],
            ['distrito_id'  =>  1, 'municipio' => 'Cotaxtla', 'clave' => '49'],
            ['distrito_id'  =>  1, 'municipio' => 'Coxquihui', 'clave' => '50'],
            ['distrito_id'  =>  1, 'municipio' => 'Coyutla', 'clave' => '51'],
            ['distrito_id'  =>  1, 'municipio' => 'Cuichapa', 'clave' => '52'],
            ['distrito_id'  =>  1, 'municipio' => 'Cuitláhuac', 'clave' => '53'],
            ['distrito_id'  =>  1, 'municipio' => 'Chacaltianguis', 'clave' => '54'],
            ['distrito_id'  =>  1, 'municipio' => 'Chalma', 'clave' => '55'],
            ['distrito_id'  =>  1, 'municipio' => 'Chiconamel', 'clave' => '56'],
            ['distrito_id'  =>  1, 'municipio' => 'Chiconquiaco', 'clave' => '57'],
            ['distrito_id'  =>  1, 'municipio' => 'Chicontepec', 'clave' => '58'],
            ['distrito_id'  =>  1, 'municipio' => 'Chinameca', 'clave' => '59'],
            ['distrito_id'  =>  1, 'municipio' => 'Chinampa de Gorostiza', 'clave' => '60'],
            ['distrito_id'  =>  1, 'municipio' => 'Las Choapas', 'clave' => '61'],
            ['distrito_id'  =>  1, 'municipio' => 'Chocamán', 'clave' => '62'],
            ['distrito_id'  =>  1, 'municipio' => 'Chontla', 'clave' => '63'],
            ['distrito_id'  =>  1, 'municipio' => 'Chumatlán', 'clave' => '64'],
            ['distrito_id'  =>  1, 'municipio' => 'Emiliano Zapata', 'clave' => '65'],
            ['distrito_id'  =>  1, 'municipio' => 'Espinal', 'clave' => '66'],
            ['distrito_id'  =>  1, 'municipio' => 'Filomeno Mata', 'clave' => '67'],
            ['distrito_id'  =>  1, 'municipio' => 'Fortín', 'clave' => '68'],
            ['distrito_id'  =>  1, 'municipio' => 'Gutiérrez Zamora', 'clave' => '69'],
            ['distrito_id'  =>  1, 'municipio' => 'Hidalgotitlán', 'clave' => '70'],
            ['distrito_id'  =>  1, 'municipio' => 'Huatusco', 'clave' => '71'],
            ['distrito_id'  =>  1, 'municipio' => 'Huayacocotla', 'clave' => '72'],
            ['distrito_id'  =>  1, 'municipio' => 'Hueyapan de Ocampo', 'clave' => '73'],
            ['distrito_id'  =>  1, 'municipio' => 'Huiloapan de Cuauhtémoc', 'clave' => '74'],
            ['distrito_id'  =>  1, 'municipio' => 'Ignacio de la Llave', 'clave' => '75'],
            ['distrito_id'  =>  1, 'municipio' => 'Ilamatlán', 'clave' => '76'],
            ['distrito_id'  =>  1, 'municipio' => 'Isla', 'clave' => '77'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixcatepec', 'clave' => '78'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixhuacán de los Reyes', 'clave' => '79'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixhuatlán del Café', 'clave' => '80'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixhuatlancillo', 'clave' => '81'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixhuatlán del Sureste', 'clave' => '82'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixhuatlán de Madero', 'clave' => '83'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixmatlahuacan', 'clave' => '84'],
            ['distrito_id'  =>  1, 'municipio' => 'Ixtaczoquitlán', 'clave' => '85'],
            ['distrito_id'  =>  1, 'municipio' => 'Jalacingo', 'clave' => '86'],
            ['distrito_id'  =>  1, 'municipio' => 'Xalapa', 'clave' => '87'],
            ['distrito_id'  =>  1, 'municipio' => 'Jalcomulco', 'clave' => '88'],
            ['distrito_id'  =>  1, 'municipio' => 'Jáltipan', 'clave' => '89'],
            ['distrito_id'  =>  1, 'municipio' => 'Jamapa', 'clave' => '90'],
            ['distrito_id'  =>  1, 'municipio' => 'Jesús Carranza', 'clave' => '91'],
            ['distrito_id'  =>  1, 'municipio' => 'Xico', 'clave' => '92'],
            ['distrito_id'  =>  1, 'municipio' => 'Jilotepec', 'clave' => '93'],
            ['distrito_id'  =>  1, 'municipio' => 'Juan Rodríguez Clara', 'clave' => '94'],
            ['distrito_id'  =>  1, 'municipio' => 'Juchique de Ferrer', 'clave' => '95'],
            ['distrito_id'  =>  1, 'municipio' => 'Landero y Coss', 'clave' => '96'],
            ['distrito_id'  =>  1, 'municipio' => 'Lerdo de Tejada', 'clave' => '97'],
            ['distrito_id'  =>  1, 'municipio' => 'Magdalena', 'clave' => '98'],
            ['distrito_id'  =>  1, 'municipio' => 'Maltrata', 'clave' => '99'],
            ['distrito_id'  =>  1, 'municipio' => 'Manlio Fabio Altamirano', 'clave' => '100'],
            ['distrito_id'  =>  1, 'municipio' => 'Mariano Escobedo', 'clave' => '101'],
            ['distrito_id'  =>  1, 'municipio' => 'Martínez de la Torre', 'clave' => '102'],
            ['distrito_id'  =>  1, 'municipio' => 'Mecatlán', 'clave' => '103'],
            ['distrito_id'  =>  1, 'municipio' => 'Mecayapan', 'clave' => '104'],
            ['distrito_id'  =>  1, 'municipio' => 'Medellín de Bravo', 'clave' => '105'],
            ['distrito_id'  =>  1, 'municipio' => 'Miahuatlán', 'clave' => '106'],
            ['distrito_id'  =>  1, 'municipio' => 'Las Minas', 'clave' => '107'],
            ['distrito_id'  =>  1, 'municipio' => 'Minatitlán', 'clave' => '108'],
            ['distrito_id'  =>  1, 'municipio' => 'Misantla', 'clave' => '109'],
            ['distrito_id'  =>  1, 'municipio' => 'Mixtla de Altamirano', 'clave' => '110'],
            ['distrito_id'  =>  1, 'municipio' => 'Moloacán', 'clave' => '111'],
            ['distrito_id'  =>  1, 'municipio' => 'Naolinco', 'clave' => '112'],
            ['distrito_id'  =>  1, 'municipio' => 'Naranjal', 'clave' => '113'],
            ['distrito_id'  =>  1, 'municipio' => 'Nautla', 'clave' => '114'],
            ['distrito_id'  =>  1, 'municipio' => 'Nogales', 'clave' => '115'],
            ['distrito_id'  =>  1, 'municipio' => 'Oluta', 'clave' => '116'],
            ['distrito_id'  =>  1, 'municipio' => 'Omealca', 'clave' => '117'],
            ['distrito_id'  =>  1, 'municipio' => 'Orizaba', 'clave' => '118'],
            ['distrito_id'  =>  1, 'municipio' => 'Otatitlán', 'clave' => '119'],
            ['distrito_id'  =>  1, 'municipio' => 'Oteapan', 'clave' => '120'],
            ['distrito_id'  =>  1, 'municipio' => 'Ozuluama de Mascareñas', 'clave' => '121'],
            ['distrito_id'  =>  1, 'municipio' => 'Pajapan', 'clave' => '122'],
            ['distrito_id'  =>  1, 'municipio' => 'Pánuco', 'clave' => '123'],
            ['distrito_id'  =>  1, 'municipio' => 'Papantla', 'clave' => '124'],
            ['distrito_id'  =>  1, 'municipio' => 'Paso del Macho', 'clave' => '125'],
            ['distrito_id'  =>  1, 'municipio' => 'Paso de Ovejas', 'clave' => '126'],
            ['distrito_id'  =>  1, 'municipio' => 'La Perla', 'clave' => '127'],
            ['distrito_id'  =>  1, 'municipio' => 'Perote', 'clave' => '128'],
            ['distrito_id'  =>  1, 'municipio' => 'Platón Sánchez', 'clave' => '129'],
            ['distrito_id'  =>  1, 'municipio' => 'Playa Vicente', 'clave' => '130'],
            ['distrito_id'  =>  1, 'municipio' => 'Poza Rica de Hidalgo', 'clave' => '131'],
            ['distrito_id'  =>  1, 'municipio' => 'Las Vigas de Ramírez', 'clave' => '132'],
            ['distrito_id'  =>  1, 'municipio' => 'Pueblo Viejo', 'clave' => '133'],
            ['distrito_id'  =>  1, 'municipio' => 'Puente Nacional', 'clave' => '134'],
            ['distrito_id'  =>  1, 'municipio' => 'Rafael Delgado', 'clave' => '135'],
            ['distrito_id'  =>  1, 'municipio' => 'Rafael Lucio', 'clave' => '136'],
            ['distrito_id'  =>  1, 'municipio' => 'Los Reyes', 'clave' => '137'],
            ['distrito_id'  =>  1, 'municipio' => 'Río Blanco', 'clave' => '138'],
            ['distrito_id'  =>  1, 'municipio' => 'Saltabarranca', 'clave' => '139'],
            ['distrito_id'  =>  1, 'municipio' => 'San Andrés Tenejapan', 'clave' => '140'],
            ['distrito_id'  =>  1, 'municipio' => 'San Andrés Tuxtla', 'clave' => '141'],
            ['distrito_id'  =>  1, 'municipio' => 'San Juan Evangelista', 'clave' => '142'],
            ['distrito_id'  =>  1, 'municipio' => 'Santiago Tuxtla', 'clave' => '143'],
            ['distrito_id'  =>  1, 'municipio' => 'Sayula de Alemán', 'clave' => '144'],
            ['distrito_id'  =>  1, 'municipio' => 'Soconusco', 'clave' => '145'],
            ['distrito_id'  =>  1, 'municipio' => 'Sochiapa', 'clave' => '146'],
            ['distrito_id'  =>  1, 'municipio' => 'Soledad Atzompa', 'clave' => '147'],
            ['distrito_id'  =>  1, 'municipio' => 'Soledad de Doblado', 'clave' => '148'],
            ['distrito_id'  =>  1, 'municipio' => 'Soteapan', 'clave' => '149'],
            ['distrito_id'  =>  1, 'municipio' => 'Tamalín', 'clave' => '150'],
            ['distrito_id'  =>  1, 'municipio' => 'Tamiahua', 'clave' => '151'],
            ['distrito_id'  =>  1, 'municipio' => 'Tampico Alto', 'clave' => '152'],
            ['distrito_id'  =>  1, 'municipio' => 'Tancoco', 'clave' => '153'],
            ['distrito_id'  =>  1, 'municipio' => 'Tantima', 'clave' => '154'],
            ['distrito_id'  =>  1, 'municipio' => 'Tantoyuca', 'clave' => '155'],
            ['distrito_id'  =>  1, 'municipio' => 'Tatatila', 'clave' => '156'],
            ['distrito_id'  =>  1, 'municipio' => 'Castillo de Teayo', 'clave' => '157'],
            ['distrito_id'  =>  1, 'municipio' => 'Tecolutla', 'clave' => '158'],
            ['distrito_id'  =>  1, 'municipio' => 'Tehuipango', 'clave' => '159'],
            ['distrito_id'  =>  1, 'municipio' => 'Álamo Temapache', 'clave' => '160'],
            ['distrito_id'  =>  1, 'municipio' => 'Tempoal', 'clave' => '161'],
            ['distrito_id'  =>  1, 'municipio' => 'Tenampa', 'clave' => '162'],
            ['distrito_id'  =>  1, 'municipio' => 'Tenochtitlán', 'clave' => '163'],
            ['distrito_id'  =>  1, 'municipio' => 'Teocelo', 'clave' => '164'],
            ['distrito_id'  =>  1, 'municipio' => 'Tepatlaxco', 'clave' => '165'],
            ['distrito_id'  =>  1, 'municipio' => 'Tepetlán', 'clave' => '166'],
            ['distrito_id'  =>  1, 'municipio' => 'Tepetzintla', 'clave' => '167'],
            ['distrito_id'  =>  1, 'municipio' => 'Tequila', 'clave' => '168'],
            ['distrito_id'  =>  1, 'municipio' => 'José Azueta', 'clave' => '169'],
            ['distrito_id'  =>  1, 'municipio' => 'Texcatepec', 'clave' => '170'],
            ['distrito_id'  =>  1, 'municipio' => 'Texhuacán', 'clave' => '171'],
            ['distrito_id'  =>  1, 'municipio' => 'Texistepec', 'clave' => '172'],
            ['distrito_id'  =>  1, 'municipio' => 'Tezonapa', 'clave' => '173'],
            ['distrito_id'  =>  1, 'municipio' => 'Tierra Blanca', 'clave' => '174'],
            ['distrito_id'  =>  1, 'municipio' => 'Tihuatlán', 'clave' => '175'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlacojalpan', 'clave' => '176'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlacolulan', 'clave' => '177'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlacotalpan', 'clave' => '178'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlacotepec de Mejía', 'clave' => '179'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlachichilco', 'clave' => '180'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlalixcoyan', 'clave' => '181'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlalnelhuayocan', 'clave' => '182'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlapacoyan', 'clave' => '183'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlaquilpa', 'clave' => '184'],
            ['distrito_id'  =>  1, 'municipio' => 'Tlilapan', 'clave' => '185'],
            ['distrito_id'  =>  1, 'municipio' => 'Tomatlán', 'clave' => '186'],
            ['distrito_id'  =>  1, 'municipio' => 'Tonayán', 'clave' => '187'],
            ['distrito_id'  =>  1, 'municipio' => 'Totutla', 'clave' => '188'],
            ['distrito_id'  =>  1, 'municipio' => 'Tuxpan', 'clave' => '189'],
            ['distrito_id'  =>  1, 'municipio' => 'Tuxtilla', 'clave' => '190'],
            ['distrito_id'  =>  1, 'municipio' => 'Ursulo Galván', 'clave' => '191'],
            ['distrito_id'  =>  1, 'municipio' => 'Vega de Alatorre', 'clave' => '192'],
            ['distrito_id'  =>  1, 'municipio' => 'Veracruz', 'clave' => '193'],
            ['distrito_id'  =>  1, 'municipio' => 'Villa Aldama', 'clave' => '194'],
            ['distrito_id'  =>  1, 'municipio' => 'Xoxocotla', 'clave' => '195'],
            ['distrito_id'  =>  1, 'municipio' => 'Yanga', 'clave' => '196'],
            ['distrito_id'  =>  1, 'municipio' => 'Yecuatla', 'clave' => '197'],
            ['distrito_id'  =>  1, 'municipio' => 'Zacualpan', 'clave' => '198'],
            ['distrito_id'  =>  1, 'municipio' => 'Zaragoza', 'clave' => '199'],
            ['distrito_id'  =>  1, 'municipio' => 'Zentla', 'clave' => '200'],
            ['distrito_id'  =>  1, 'municipio' => 'Zongolica', 'clave' => '201'],
            ['distrito_id'  =>  1, 'municipio' => 'Zontecomatlán de López y Fuentes', 'clave' => '202'],
            ['distrito_id'  =>  1, 'municipio' => 'Zozocolco de Hidalgo', 'clave' => '203'],
            ['distrito_id'  =>  1, 'municipio' => 'Agua Dulce', 'clave' => '204'],
            ['distrito_id'  =>  1, 'municipio' => 'El Higo', 'clave' => '205'],
            ['distrito_id'  =>  1, 'municipio' => 'Nanchital de Lázaro Cárdenas del Río', 'clave' => '206'],
            ['distrito_id'  =>  1, 'municipio' => 'Tres Valles', 'clave' => '207'],
            ['distrito_id'  =>  1, 'municipio' => 'Carlos A. Carrillo', 'clave' => '208'],
            ['distrito_id'  =>  1, 'municipio' => 'Tatahuicapan de Juárez', 'clave' => '209'],
            ['distrito_id'  =>  1, 'municipio' => 'Uxpanapa', 'clave' => '210'],
            ['distrito_id'  =>  1, 'municipio' => 'San Rafael', 'clave' => '211'],
            ['distrito_id'  =>  1, 'municipio' => 'Santiago Sochiapan', 'clave' => '212']
        ]);
    }
}
